### PR TITLE
Update Python and Git Links

### PR DESCRIPTION
**Pull request by TaylorBeebe**

### CODE REVIEW

**Comment by makubacki** [comment]
Do we really need to reference specific versions? Or can we just say get the latest from the generic links which already highlight the latest release?

- https://www.python.org/downloads/
- https://github.com/git-for-windows/git/releases

I think if we went that direction, we could end up having to update this a lot less. Only when the latest is known to cause a problem.

**Comment by TaylorBeebe** [comment]
> Do we really need to reference specific versions? Or can we just say get the latest from the generic links which already highlight the latest release?
> 
> * https://www.python.org/downloads/
> * https://github.com/git-for-windows/git/releases
> 
> I think if we went that direction, we could end up having to update this a lot less. Only when the latest is known to cause a problem.

I say we just complete this and keep your suggestion in mind for next time :)

**Review by spbrogan — APPROVED** [review]

**Comment by spbrogan** [comment]
if you look at the doc it already has a link to download site where user can get latest.  The version taylor updated is just an example.  I don't think we need to update too regularly.  If we have strong dependencies then we probably should update...otherwise no need.

**Comment by makubacki** [comment]
> > Do we really need to reference specific versions? Or can we just say get the latest from the generic links which already highlight the latest release?
> > 
> > * https://www.python.org/downloads/
> > * https://github.com/git-for-windows/git/releases
> > 
> > I think if we went that direction, we could end up having to update this a lot less. Only when the latest is known to cause a problem.
> 
> I say we just complete this and keep your suggestion in mind for next time :)

Sure, I don't see value in specifying the latest version when "Download latest Python" is already stated. Either the example given is the latest version or that statement is incorrect and confusing. But, if we want to update this every time a new Python version is released so tthe document makes sense, that's fine too.

Ultimately, I think the Python version really should be the one used in CI though because that's the one being regularly tested.

**Comment by makubacki** [comment]
> if you look at the doc it already has a link to download site where user can get latest. The version taylor updated is just an example. I don't think we need to update too regularly. If we have strong dependencies then we probably should update...otherwise no need.

Yes, I saw the link and the text that already states, "Download latest Python from <https://www.python.org/downloads>". I was trying to say that "Download latest Python" with a link to the latest version followed by an example with a fixed version invites the two getting out of sync (as they previously were).

When they are out of sync, it's not clear which version to actually use. In that case, I think the example is actually more confusing than it is helpful since it's just a path to the Windows executable which can be found on the downloads page already linked.

**Pull request merged**
