### PR TITLE
Update azure pipeline node version

### PR DESCRIPTION
**Pull request by Javagedes**
Update azure pipeline node version to the newest major version (17.x). Additional spelling fixes made where required.

### CODE REVIEW

**Review by spbrogan — CHANGES_REQUESTED** [review]
I think node is now at 17 or something much larger.  Can you set it to newer so that we don't age out again soon.

**Review by spbrogan — APPROVED** [review]
thanks

**Comment by spbrogan** [comment]
you are going to need to fix the newly detected spelling issues. 

12/22 .\docs\How\integration_checklist.md 68.25ms X
d:\a\1\s\docs\How\integration_checklist.md:47:34 - Unknown word (gitignores)
d:\a\1\s\docs\How\integration_checklist.md:59:40 - Unknown word (TCMORPH)
d:\a\1\s\docs\How\integration_checklist.md:88:50 - Unknown word (extdep)

**Comment by Javagedes** [comment]
Flake8 is not being installed. Will fix.

**Review by spbrogan — APPROVED** [review]

**Pull request merged**
